### ISSUE TITLE
Support bit.ly links

### ISSUE THREAD

**Issue by aegroto** [impredicative/bitlyshortener#13]
Hello! I've used this library for months but I've always had a doubt: why doesn't it support bit.ly links but only j.mp ones? What would require to support other link formats as well?

**Comment by impredicative** [comment]
All `j.mp` links are `bit.ly` links, and vice versa. In other words, to get a `bit.ly` link from a `j.mp` link, one can use text replacement, as for example: `"https://j.mp/39Ui8UJ".replace("/j.mp/", "/bit.ly/", 1)`. I hope this works for you. `j.mp` is used simply because it is the shortest of these short links.

**Comment by impredicative** [comment]
You may wish to refer to the optional `vanitize=True` feature documented in the readme. This adds support for custom domains, e.g. `cnn.it`, `amzn.to`, etc.

**Comment by impredicative** [comment]
FYI: A bug was fixed in v0.4.2.

**Comment by impredicative** [comment]
v0.5.0 always in effect uses the vanitize mode. That's because forcing the j.mp or bit.ly URLs for vanity domains is no longer supported by Bitly. Refer to the examples in the readme.
